# Generated by Django 5.1.5 on 2025-01-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technologies', '0002_alter_technology_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('technologies', models.ManyToManyField(to='technologies.technology')),
            ],
        ),
    ]
